import type { Project, Task, Tag } from "../types/projectTypes";

const BASE = "/api";

function getAuthHeaders(): Record<string, string> {
  const token = localStorage.getItem("auth_token") ?? "";
  return token ? { Authorization: `Bearer ${token}` } : {};
}

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    headers: {
      "Content-Type": "application/json",
      ...getAuthHeaders(),
    },
    ...options,
  });
  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new Error(`${res.status}: ${text}`);
  }
  // 204 No Content — nothing to parse
  if (res.status === 204) return undefined as T;
  const data = await res.json();
  console.log(`[api] ${options?.method ?? "GET"} ${path}`, data);
  return data as T;
}

// ── Normalizers ───────────────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function normalizeProject(raw: any): Project {
  return {
    id:         String(raw.id ?? raw._id ?? raw.projeto_id ?? ""),
    name:       raw.name ?? raw.nome ?? raw.titulo ?? "",
    user_id:    String(raw.user_id ?? raw.usuario_id ?? ""),
    created_at: raw.created_at ?? raw.criado_em ?? Date.now(),
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function normalizeTask(raw: any): Task {
  return {
    id:         String(raw.id ?? raw._id ?? raw.tarefa_id ?? ""),
    project_id: String(raw.project_id ?? raw.projeto_id ?? ""),
    title:      raw.title ?? raw.titulo ?? raw.name ?? "",
    status:     raw.status ?? "todo",
    tags:       Array.isArray(raw.tags) ? raw.tags.map(String) : [],
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function normalizeTag(raw: any): Tag {
  return {
    id:         String(raw.id ?? raw._id ?? raw.tag_id ?? ""),
    project_id: String(raw.project_id ?? raw.projeto_id ?? ""),
    name:       raw.name ?? raw.nome ?? "",
    color:      raw.color ?? raw.cor ?? "#4a6fa5",
  };
}

// ── Graph response ─────────────────────────────────────────────────────────────
// GET /projects/:id/graph returns { project, graphData }
// project: { id, name, user_id, created_at, tasks: [...], tags: [...] }
// graphData: { nodes, links } — generated by Project.toGraphData(), not used directly

export interface ProjectGraphData {
  project: Project;
  tasks: Task[];
  tags: Tag[];
}

export async function fetchProjectGraph(projectId: string): Promise<ProjectGraphData> {
  const res = await request<{
    project: Record<string, unknown>;
    graphData: unknown;
  }>(`/projects/${projectId}/graph`);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const raw = res.project as any;

  const project = normalizeProject(raw);
  const tasks   = (Array.isArray(raw.tasks) ? raw.tasks : []).map(normalizeTask);

  // Deduplicate tags — same tag can appear multiple times via task_tags join
  const tagMap = new Map<string, Tag>();
  (Array.isArray(raw.tags) ? raw.tags : []).forEach((t: unknown) => {
    const tag = normalizeTag(t);
    if (tag.id && !tagMap.has(tag.id)) tagMap.set(tag.id, tag);
  });

  return { project, tasks, tags: Array.from(tagMap.values()) };
}

// ── Projects ──────────────────────────────────────────────────────────────────

export async function fetchProjects(): Promise<Project[]> {
  const data = await request<unknown[]>("/projects");
  return (Array.isArray(data) ? data : []).map(normalizeProject);
}

export async function createProject(name: string): Promise<Project> {
  // API returns { message: "...", project: {...} }
  const data = await request<{ project?: unknown } & Record<string, unknown>>("/projects", {
    method: "POST",
    body: JSON.stringify({ name }),
  });
  return normalizeProject(data.project ?? data);
}

export async function deleteProject(id: string): Promise<void> {
  await request(`/projects/${id}`, { method: "DELETE" });
}

// ── Tasks ─────────────────────────────────────────────────────────────────────
// NOTE: backend routes for tasks/tags don't exist yet.
// These are stubs — implement when backend routes are added.

export async function fetchTasks(projectId: string): Promise<Task[]> {
  // Tasks come from /projects/:id/graph — use fetchProjectGraph instead
  const { tasks } = await fetchProjectGraph(projectId);
  return tasks;
}

export async function fetchTags(projectId: string): Promise<Tag[]> {
  // Tags come from /projects/:id/graph — use fetchProjectGraph instead
  const { tags } = await fetchProjectGraph(projectId);
  return tags;
}

export async function createTask(
  projectId: string,
  payload: Omit<Task, "id" | "project_id">
): Promise<Task> {
  // TODO: implement when backend adds POST /projects/:id/tasks
  const data = await request<unknown>(`/projects/${projectId}/tasks`, {
    method: "POST",
    body: JSON.stringify(payload),
  });
  return normalizeTask(data);
}

export async function updateTask(task: Task): Promise<Task> {
  const data = await request<unknown>(`/projects/${task.project_id}/tasks/${task.id}`, {
    method: "PUT",
    body: JSON.stringify({
      title:  task.title,
      status: task.status,
      tags:   task.tags.map(Number), // backend expects integer tag ids
    }),
  });
  return normalizeTask(data);
}

export async function deleteTask(task: Task): Promise<void> {
  await request<void>(`/projects/${task.project_id}/tasks/${task.id}`, {
    method: "DELETE",
  });
}

// ── Tags ──────────────────────────────────────────────────────────────────────

export async function createTag(
  projectId: string,
  payload: Omit<Tag, "id" | "project_id">
): Promise<Tag> {
  const data = await request<unknown>(`/projects/${projectId}/tags`, {
    method: "POST",
    body: JSON.stringify(payload),
  });
  return normalizeTag(data);
}

export async function deleteTag(projectId: string, tagId: string): Promise<void> {
  await request<void>(`/projects/${projectId}/tags/${tagId}`, { method: "DELETE" });
}